export const siteConfig = {
  brandName: 'GS ART',
  slogan: "L'art de créer autrement.",
  phone: '+237 693 037 919',
  whatsapp: '237693037919',
  email: 'gsartresine@gmail.com',
  city: 'Bafoussam · Douala',
  country: 'Cameroun',
  address: 'tatianagounou@gmail.com',
  instagram: 'https://www.instagram.com/gsresine?stkn=YjFwdDNrb3NjaGx3',
  facebook: 'https://www.facebook.com/profile.php?id=61594229627587',
  tiktok: 'https://www.tiktok.com/@gsartresine?_r=1&_t=ZP-9A9sB5GUBqg',
  linkedin: 'https://www.linkedin.com/posts/ideogram-ai_introducing-ideogram-45-the-most-precise-ugcPost-7511092976526213120-c4iv',
  snaptchat: 'https://www.snapchat.com/add/gsartresine?share_id=c-EfRsWdS9Y&locale=fr-FR',
} as const;
